[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "metetl_LuchinMD_6305"
version = "0.1.0"
description = "Пакет для обработки и анализа данных Метрополитен-музея"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "LuchinMD", email = "m_luchin@mail.ru" }
]
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "opencv-python",
    "aiohttp",
    "aiofiles"
]

[project.scripts]
metetl = "metetl.main:main"